name: UI Tests (Tablet-Public-Cart-Disabled)

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests (Tablet-Public-Cart-Disabled)
        run: |
          echo "Running tests on tablet"
          npx playwright test guest-tablet-public-test.spec.ts learner-tablet-public-test.spec.ts --headed --project=chromium-tablet
        env:
          publicBaseUrl: ${{ secrets.PUBLIC_BASE_URL }}
          environment: ${{ secrets.ENVIRONMENT }}
          publicLearnerUsername: ${{ secrets.PUBLIC_LEARNER_USERNAME }}
          publicLearnerPassword: ${{ secrets.PUBLIC_LEARNER_PASSWORD }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
